### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by thorduri** [alindeman/butteredscones#6]
No explicit license in the repository as far as I can tell.

I.e. no LICENSE file, and each individual file does not seem to contain a license header.

**Comment by alindeman** [comment]
You're right. We meant for this to be MIT-licensed, but had forgotten to add a file. It's fixed now.

**Comment by thorduri** [comment]
Thanks!

On Thu, Feb 12, 2015 at 4:35 PM, alindeman <notifications@github.com> wrote:

> You're right. We meant for this to be MIT-licensed, but had forgotten to
> add a file. It's fixed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alindeman/butteredscones/issues/6#issuecomment-74090791>
> .
>



-- 
/ciao, thorduri.
